require('dotenv/config');

const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');

const books = [
  {
    codigo: 'INF-001',
    titulo: 'Fundamentos de Programacion',
    autor: 'Luis Joyanes Aguilar',
    anio: 2021,
    categoria: 'Informatica',
    programa: 'Desarrollo de Software',
    editorial: 'McGraw Hill',
    isbn: '9788448198445',
    totalEjemplares: 6,
    disponibles: 6,
    descripcion: 'Introduccion practica a algoritmos, estructuras basicas y pensamiento computacional.',
  },
  {
    codigo: 'ADM-014',
    titulo: 'Administracion Moderna',
    autor: 'Stephen Robbins',
    anio: 2020,
    categoria: 'Administracion',
    programa: 'Gestion Empresarial',
    editorial: 'Pearson',
    isbn: '9786073243371',
    totalEjemplares: 4,
    disponibles: 4,
    descripcion: 'Conceptos actuales de gestion, liderazgo, control y toma de decisiones.',
  },
  {
    codigo: 'CON-022',
    titulo: 'Contabilidad General',
    autor: 'Pedro Zapata Sanchez',
    anio: 2019,
    categoria: 'Contabilidad',
    programa: 'Contabilidad y Auditoria',
    editorial: 'Ecoe Ediciones',
    isbn: '9789587718471',
    totalEjemplares: 5,
    disponibles: 5,
    descripcion: 'Registro contable, estados financieros y ejercicios de aplicacion.',
  },
  {
    codigo: 'EDU-008',
    titulo: 'Didactica General',
    autor: 'Antonio Medina Rivilla',
    anio: 2018,
    categoria: 'Educacion',
    programa: 'Educacion Basica',
    editorial: 'Pearson',
    isbn: '9788483225212',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Estrategias de ensenanza, planificacion y evaluacion del aprendizaje.',
  },
  {
    codigo: 'MAT-030',
    titulo: 'Matematica Aplicada',
    autor: 'Erwin Kreyszig',
    anio: 2022,
    categoria: 'Matematica',
    programa: 'Ciencias Basicas',
    editorial: 'Wiley',
    isbn: '9781119455929',
    totalEjemplares: 4,
    disponibles: 4,
    descripcion: 'Herramientas matematicas para resolver problemas tecnicos y administrativos.',
  },
  {
    codigo: 'SOFT-101',
    titulo: 'Clean Code',
    autor: 'Robert C. Martin',
    anio: 2008,
    categoria: 'Programacion',
    programa: 'Desarrollo de Software',
    editorial: 'Prentice Hall',
    isbn: '9780132350884',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Buenas practicas para escribir codigo claro, mantenible y profesional.',
  },
  {
    codigo: 'SOFT-102',
    titulo: 'The Pragmatic Programmer',
    autor: 'Andrew Hunt y David Thomas',
    anio: 2019,
    categoria: 'Programacion',
    programa: 'Desarrollo de Software',
    editorial: 'Addison-Wesley',
    isbn: '9780135957059',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Consejos practicos para pensar, construir y mejorar software con criterio.',
  },
  {
    codigo: 'SOFT-103',
    titulo: 'Inteligencia Artificial: Un Enfoque Moderno',
    autor: 'Stuart Russell y Peter Norvig',
    anio: 2021,
    categoria: 'Inteligencia Artificial',
    programa: 'Desarrollo de Software',
    editorial: 'Pearson',
    isbn: '9788490358662',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Fundamentos de IA, busqueda, aprendizaje automatico y agentes inteligentes.',
  },
  {
    codigo: 'SOFT-104',
    titulo: 'Designing Data-Intensive Applications',
    autor: 'Martin Kleppmann',
    anio: 2017,
    categoria: 'Bases de Datos',
    programa: 'Desarrollo de Software',
    editorial: 'O Reilly Media',
    isbn: '9781449373320',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Arquitectura de datos, escalabilidad, consistencia y sistemas distribuidos.',
  },
  {
    codigo: 'DIS-201',
    titulo: 'No Me Hagas Pensar',
    autor: 'Steve Krug',
    anio: 2014,
    categoria: 'Diseno UX',
    programa: 'Diseno Grafico',
    editorial: 'New Riders',
    isbn: '9780321965516',
    totalEjemplares: 4,
    disponibles: 4,
    descripcion: 'Guia directa para crear interfaces simples, claras y faciles de usar.',
  },
  {
    codigo: 'DIS-202',
    titulo: 'El Diseno Como Storytelling',
    autor: 'Ellen Lupton',
    anio: 2017,
    categoria: 'Diseno',
    programa: 'Diseno Grafico',
    editorial: 'Cooper Hewitt',
    isbn: '9781942303190',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Tecnicas para comunicar ideas visuales mediante narrativa y experiencia.',
  },
  {
    codigo: 'EMP-301',
    titulo: 'La Estrategia del Oceano Azul',
    autor: 'W. Chan Kim y Renee Mauborgne',
    anio: 2015,
    categoria: 'Estrategia',
    programa: 'Gestion Empresarial',
    editorial: 'Harvard Business Review Press',
    isbn: '9781625274496',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Herramientas para crear mercados nuevos y diferenciar una propuesta de valor.',
  },
  {
    codigo: 'EMP-302',
    titulo: 'El Metodo Lean Startup',
    autor: 'Eric Ries',
    anio: 2011,
    categoria: 'Emprendimiento',
    programa: 'Gestion Empresarial',
    editorial: 'Crown Business',
    isbn: '9780307887894',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Modelo para validar ideas, medir avances y construir productos viables.',
  },
  {
    codigo: 'CON-303',
    titulo: 'Finanzas Para Emprendedores',
    autor: 'Antonio Manzanera',
    anio: 2016,
    categoria: 'Finanzas',
    programa: 'Contabilidad y Auditoria',
    editorial: 'Deusto',
    isbn: '9788423425181',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Conceptos financieros utiles para evaluar inversiones, costos y crecimiento.',
  },
  {
    codigo: 'EDU-401',
    titulo: 'Ensenar a Pensar',
    autor: 'Robert Swartz',
    anio: 2017,
    categoria: 'Educacion',
    programa: 'Educacion Basica',
    editorial: 'SM',
    isbn: '9788467594938',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Estrategias para desarrollar pensamiento critico dentro del aula.',
  },
  {
    codigo: 'EDU-402',
    titulo: 'Aprendizaje Basado en Proyectos',
    autor: 'John Larmer, John Mergendoller y Suzie Boss',
    anio: 2015,
    categoria: 'Educacion',
    programa: 'Educacion Basica',
    editorial: 'Buck Institute for Education',
    isbn: '9781416620334',
    totalEjemplares: 2,
    disponibles: 2,
    descripcion: 'Guia para planificar experiencias de aprendizaje activas y significativas.',
  },
  {
    codigo: 'CIE-501',
    titulo: 'Breves Respuestas a las Grandes Preguntas',
    autor: 'Stephen Hawking',
    anio: 2018,
    categoria: 'Ciencia',
    programa: 'Ciencias Basicas',
    editorial: 'Critica',
    isbn: '9788491990434',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Reflexiones sobre universo, tecnologia, inteligencia artificial y futuro humano.',
  },
  {
    codigo: 'LIT-601',
    titulo: 'Cien Anos de Soledad',
    autor: 'Gabriel Garcia Marquez',
    anio: 1967,
    categoria: 'Literatura',
    programa: 'Coleccion General',
    editorial: 'Sudamericana',
    isbn: '9780307474728',
    totalEjemplares: 4,
    disponibles: 4,
    descripcion: 'Novela esencial del realismo magico latinoamericano y la familia Buendia.',
  },
  {
    codigo: 'LIT-602',
    titulo: 'El Principito',
    autor: 'Antoine de Saint-Exupery',
    anio: 1943,
    categoria: 'Literatura',
    programa: 'Coleccion General',
    editorial: 'Reynal & Hitchcock',
    isbn: '9780156012195',
    totalEjemplares: 5,
    disponibles: 5,
    descripcion: 'Relato breve sobre amistad, imaginacion, responsabilidad y mirada humana.',
  },
  {
    codigo: 'SOC-701',
    titulo: 'Sapiens: De Animales a Dioses',
    autor: 'Yuval Noah Harari',
    anio: 2014,
    categoria: 'Historia',
    programa: 'Coleccion General',
    editorial: 'Debate',
    isbn: '9788499926223',
    totalEjemplares: 3,
    disponibles: 3,
    descripcion: 'Recorrido por la historia humana, la cultura, la economia y la tecnologia.',
  },
];

async function main() {
  if (!process.env.DATABASE_URL) {
    console.error('Falta DATABASE_URL en .env. Configura PostgreSQL antes de crear libros.');
    process.exit(1);
  }

  const prisma = new PrismaClient({
    adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
  });

  for (const book of books) {
    await prisma.libro.upsert({
      where: { codigo: book.codigo },
      update: book,
      create: book,
    });
  }

  await prisma.$disconnect();
  console.log('Libros de presentacion listos.');
}

main().catch((error) => {
  console.error('No se pudieron crear los libros.');
  if (
    error.message.includes('does not exist in the current database') ||
    error.message.includes('not available')
  ) {
    console.error('Primero crea las tablas con: npx prisma migrate deploy');
    console.error('O ejecuta todo junto con: npm run setup:db');
  }
  console.error(error.message);
  process.exit(1);
});
