ALTER TABLE "Prestamo"
ADD COLUMN "fechaLimite" TIMESTAMP(3),
ADD COLUMN "estado" TEXT NOT NULL DEFAULT 'ACTIVO',
ADD COLUMN "costoBase" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "descuento" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "multa" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "costoFinal" DECIMAL(10, 2) NOT NULL DEFAULT 0;
